AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Metrics/LineLength:
  Enabled: false
  
inherit_from: .rubocop_todo.yml
